name = "Juliettine"
uuid = "f42a8b7e-ed28-475d-a83f-d1f832105fbf"
authors = ["<info@umlet.com>"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
